#!/usr/bin/env python3
import subprocess
import sys
import os

# YOUR CODE GOES here

def printTree(d) :
	if (os.path.isdir(d) == False) :
		print(d);
	else :
		for (i in os.listdir(d)) :
			printTree();

if __name__ == '__main__':
	dirs = os.listdir(os.getcwd());
	for (i = 0 in dirs) :
		printTree(i);
	
	#print(os.listdir(os.getcwd())[0]);
	# just for demo
	# subprocess.run(['tree'] + sys.argv[1:])
